version: "3.8"
services:
  app:
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: ./docker/App.Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    ports:
      - "9229:9229"
      - ${PORT}:3000
    expose:
      - ${PORT}
    command: npm run start:dev
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis

  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
volumes:
  pgdata:
